#!/usr/bin/env fish

function idem_doing -a message
    echo $message
    set -q _idem_doing
end

function idem_symlink -a target path
    if test -L $path
        readlink -z $path | read -z existing_target
        if test $target != $existing_target
            if idem_doing "removing existing symlink $path"
                rm $path
            else
                ls -l $path
            end
        else
            return 0
        end
    else if test -e $path
        if idem_doing "removing existing file/directory $path"
            rm -r $path
        else
            echo "==="
            ls -l $path
            echo "==="
        end
    end
    idem_doing "creating $path -> $target"
    and mkdir -p (dirname $path)
    and ln -sT $target $path
end

function idem_symlink_native
    MSYS="$MSYS winsymlinks:nativestrict" idem_symlink $argv
end

function idem_rm_symlink -a link
    if test -L $link && idem_doing "removing $link"
        rm $link
    end
end

function idem_sudo_cp -a src dest
    if test ! -e $src && idem_doing "copying $src -> $dest (with sudo)"
        sudo mkdir -p (basename $src)
        sudo cp -T $src $dest
    end
end

source $argv[1]
echo
test "$(read -P "perform the above actions? (y/N) ")" = "y" || exit 0
set _idem_doing
source $argv[1]
